// <auto-generated />
using System;
using DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HamsterWarsWASM.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220418193145_FixedPropInClasses")]
    partial class FixedPropInClasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HamsterWarsWASM.Shared.Entities.Hamster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HamsterId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Defeats")
                        .HasColumnType("int");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("FavFood")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<string>("ImgName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("Loves")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Wins")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hamsters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 2,
                            Defeats = 1,
                            Deleted = false,
                            FavFood = "",
                            Games = 1,
                            ImgName = "/images/hamsters/hamster-1.jpg",
                            IsNew = false,
                            Loves = "",
                            MatchId = 1,
                            Name = "Rasmus",
                            Wins = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 2,
                            Defeats = 0,
                            Deleted = false,
                            FavFood = "",
                            Games = 1,
                            ImgName = "/images/hamsters/hamster-2.jpg",
                            IsNew = false,
                            Loves = "",
                            MatchId = 1,
                            Name = "Patrik",
                            Wins = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 4,
                            Defeats = 0,
                            Deleted = false,
                            FavFood = "",
                            Games = 1,
                            ImgName = "/images/hamsters/hamster-3.jpg",
                            IsNew = false,
                            Loves = "",
                            MatchId = 2,
                            Name = "Pontus",
                            Wins = 1
                        },
                        new
                        {
                            Id = 4,
                            Age = 7,
                            Defeats = 1,
                            Deleted = false,
                            FavFood = "",
                            Games = 1,
                            ImgName = "/images/hamsters/hamster-4.jpg",
                            IsNew = false,
                            Loves = "",
                            MatchId = 2,
                            Name = "Mikael",
                            Wins = 0
                        },
                        new
                        {
                            Id = 5,
                            Age = 10,
                            Defeats = 1,
                            Deleted = false,
                            FavFood = "",
                            Games = 1,
                            ImgName = "/images/hamsters/hamster-5.jpg",
                            IsNew = false,
                            Loves = "",
                            MatchId = 3,
                            Name = "Claes",
                            Wins = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 6,
                            Defeats = 0,
                            Deleted = false,
                            FavFood = "",
                            Games = 1,
                            ImgName = "/images/hamsters/hamster-6.jpg",
                            IsNew = false,
                            Loves = "",
                            MatchId = 3,
                            Name = "Jimmy",
                            Wins = 1
                        });
                });

            modelBuilder.Entity("HamsterWarsWASM.Shared.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MatchId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Games")
                        .HasColumnType("int");

                    b.Property<int?>("HamsterId")
                        .HasColumnType("int");

                    b.Property<int>("LoserId")
                        .HasColumnType("int");

                    b.Property<int>("WinnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HamsterId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Games = 0,
                            LoserId = 1,
                            WinnerId = 2
                        },
                        new
                        {
                            Id = 2,
                            Games = 0,
                            LoserId = 4,
                            WinnerId = 3
                        },
                        new
                        {
                            Id = 3,
                            Games = 0,
                            LoserId = 5,
                            WinnerId = 6
                        });
                });

            modelBuilder.Entity("HamsterWarsWASM.Shared.Entities.Match", b =>
                {
                    b.HasOne("HamsterWarsWASM.Shared.Entities.Hamster", null)
                        .WithMany("Match")
                        .HasForeignKey("HamsterId");
                });

            modelBuilder.Entity("HamsterWarsWASM.Shared.Entities.Hamster", b =>
                {
                    b.Navigation("Match");
                });
#pragma warning restore 612, 618
        }
    }
}
